name: cpanel_deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        run: echo Hello, world!
        with:
          server: ftp.cliqmedia.ng
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /
